# ----------------------------------------------------------------------------
#
#  Welcome to Baml! To use this generated code, please run the following:
#
#  $ pip install baml
#
# ----------------------------------------------------------------------------

# This file was generated by BAML: please do not edit it. Instead, edit the
# BAML files and re-generate this code using: baml-cli generate
# baml-cli is available with the baml package.

import typing

import typing_extensions
from pydantic import BaseModel

CheckT = typing_extensions.TypeVar('CheckT')
CheckName = typing_extensions.TypeVar('CheckName', bound=str)


class Check(BaseModel):
    name: str
    expression: str
    status: str


class Checked(BaseModel, typing.Generic[CheckT, CheckName]):
    value: CheckT
    checks: typing.Dict[CheckName, Check]


def get_checks(checks: typing.Dict[CheckName, Check]) -> typing.List[Check]:
    return list(checks.values())


def all_succeeded(checks: typing.Dict[CheckName, Check]) -> bool:
    return all(check.status == 'succeeded' for check in get_checks(checks))


# #########################################################################
# Generated enums (0)
# #########################################################################

# #########################################################################
# Generated classes (2)
# #########################################################################


class SentimentScore(BaseModel):
    coin: typing.Union[
        typing_extensions.Literal['BTC'], typing_extensions.Literal['ETH']
    ]
    score: typing.Union[typing_extensions.Literal['1'], typing_extensions.Literal['-1']]


class SentimentScores(BaseModel):
    scores: typing.List['SentimentScore']
    reason: str


# #########################################################################
# Generated type aliases (0)
# #########################################################################
