apiVersion: v1
kind: Service
metadata:
  name: bias-monitor
  labels:
    app.kubernetes.io/name: bias-monitor
spec:
  selector:
    app.kubernetes.io/name: bias-monitor
  ports:
    - name: metrics
      port: 9090
      targetPort: metrics
  type: ClusterIP
