apiVersion: v1
kind: Service
metadata:
  name: decisioner
  labels:
    app.kubernetes.io/name: decisioner
    app.kubernetes.io/component: api
    tier: service
spec:
  type: ClusterIP
  selector:
    app.kubernetes.io/name: decisioner
  ports:
    - name: http
      port: 8080
      targetPort: http
      protocol: TCP
